services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: shopadmin
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://shopadmin:testpassword@db:5432/shop"
    depends_on:
      - db

volumes:
  postgres_data: